### ISSUE TITLE
Create Enemy Base

### ISSUE THREAD

**Issue by DiogoMendonc-a** [DiogoMendonc-a/GameOff#3]
The basis from which all enemies should grow. Can take damage, be killed.

**Comment by JoseCutileiro** [comment]
- [x]  Class inimigo 
- [x] Movimento da class inimigo genérico 
- [ ] Sprite teste de 2 inimigos
- [x] Class ataque
- [x] Estilos de ataque: Projetil
- [ ] Estilos de ataque: Espadada
- [ ] Estilo de ataque: Região de dano
- [ ] Defesas: Cura
- [ ] Defesas: Ficar mais resistente
- [ ] UI: Adicionar sistema de HP

**Comment by DiogoMendonc-a** [comment]
Good enough as it is, we can focus on making enemies
